
import FooterSignup from "./components/Footer";
import { SiteHeader } from "./components/Header";
import "./globals.css";
import { Barlow_Condensed } from 'next/font/google'

const barlow = Barlow_Condensed({ subsets: ['latin'], weight: ['300','400','500','600','700'], variable: '--font-barlow-condensed' })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={barlow.variable}>
        <SiteHeader></SiteHeader>
        {children}
        <FooterSignup></FooterSignup>
      </body>
    </html>
  );
}
